inherit_from: .rubocop_todo.yml

require:
- rubocop-performance
- rubocop-rake

# This should always correspond to the earliest non-EOL Ruby version.
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

# TODO: Re-enable this cop after TomDoc code documentation is added.
Style/Documentation:
  Enabled: false

Layout/LineLength:
  IgnoreCopDirectives: true
Metrics/BlockLength:
  AllowedMethods:
  - context
  - describe
Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
  - expect
  - let
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
