require:
- rubocop-md
- rubocop-performance
- rubocop-rake
- rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
  - lib/rspec-wait.rb
  - "*.md"
Naming/RescuedExceptionsVariableName:
  Enabled: false

RSpec/BeEq:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/IfUnlessModifier:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
